
WISELIB_PATH=/home/wiselib/wiselib

WISELIB_STABLE=$(WISELIB_PATH)/wiselib.stable
WISELIB_TESTING=$(WISELIB_PATH)/wiselib.testing

CXX=g++
LD=ld
CXXFLAGS+=-I$(WISELIB_STABLE) -I$(WISELIB_TESTING) -lpthread
LDFLAGS+=

$(TARGET): $(SOURCES)
	$(CXX) $(CXXFLAGS) $< -o $@
